FROM ubuntu:20.04

RUN apt update -y
RUN apt upgrade -y
RUN apt install sqlite3 -y
RUN apt install -y python-3 
RUN apt install -y python3-pip
RUN pip install db-sqlite3
ENV requeriments.txt /home/requerimets.txt
COPY requeriments.txt $(requeriments.txt)
RUN pip install -r requeriments.txt

WORKDIR /home/